POST  http://localhost:3001/api/card
Content-Type: application/json

{
    "title": "Card",
    "content": "Me Card",
    "outliner": {
      "style": {
        "display": "craou"
      }
    },
    "editor": {
      "style": {
        "display": "miaou"
      }
    },
    "document" : "6343e726d8a95273f35e6f12"
}