PUT  http://localhost:3001/api/card/634567a338f76846f0f93eb5
Content-Type: application/json

{
    "title": "Card",
    "content": "Me Card",
    "outliner": {
      "style": {
        "display": "plop"
      }
    },
    "editor": {
      "style": {
        "display": "mop"
      }
    }
}
