POST  http://localhost:3001/api/group
Content-Type: application/json

{
    "document": "63073baeea21e0c2acd42834",
    "contains": [{"_id": "63073bd4ea21e0c2acd4283a", "cardOrGroup": "Card"},
    { "cardOrGroup": "Card", "item":"63073bdaea21e0c2acd4283e"}]
}